### ISSUE TITLE
Possible bug: Selected Date

### ISSUE THREAD

**Issue by pauldfitzgerald** [rebeccaXam/XamForms.Controls.Calendar#20] opened 2016-12-21 11:51 UTC
Hi Rebecca, thanks for the brilliant control.
I think there may be an issue with initially selecting a date for the control.
When initializing the control if a date is selected (today's date for example)...
Firstly, when the page opens, there is no highlight on the selected date (not sure if this was intentional or not).
Secondly, if the same date (today's date) is selected (by clicking on it) it becomes highlighted, This is not too bad, but the control's Selected Date property has now become null.
After this, selecting/unselecting the same date, the logic seems fine.
I have tested on Android and Windows Universal and the issue is the same.
Please let me know if you need any more information.
Thanks again.

**Comment by rebeccaXam** [comment] 2016-12-22 15:30
Yes you are right, this is indeed a bug. For now I would recommend setting the SelectedDate after attaching the Calendar to the UI. I will release a fix for this soon.

**Comment by rebeccaXam** [comment] 2017-02-19 20:38
Should be fixed now in 1.0.8. If the problem is still their please reopen the issue.

**Closed** 2017-02-19 20:39 UTC

**Comment by differenz-system** [comment] 2017-10-27 11:29
I'm still facing issue in 1.0.8

**Comment by OlegKlym** [comment] 2017-12-26 10:25
Still have issue with selecting already selected day. On iOS and UWP SelectedDate become null, on Android - DateTime.MinValue.
