### ISSUE TITLE
"Object reference not set to an instance" exception when binding to SelectedDates Property

### ISSUE THREAD

**Issue by mahmet** [rebeccaXam/XamForms.Controls.Calendar#22] opened 2016-12-29 11:46 UTC
Hello,

When I turn on "MultiSelectDates" and bind to the "SelectedDates" Property (public ObservableCollection<DateTime> SelectedDates) I get, when opening the Calendar, an "Object reference not set to an instance of an object" exception on both iOS and Android. I am using the newest Xamarin.Forms version 2.3.3.175

**Comment by rebeccaXam** [comment] 2017-01-30 13:55
Sorry for the late reaction, but i was very busy in December and January. 

```SelectedDates``` is a List<DateTime> but its default is null. Therefore adding dates to ```SelectedDates``` without first calling ```SelectedDates = new List<Datetime>();``` will result in a "Object reference not set to an instance" exception.

I will change the default type of ```SelectedDates``` to new List<Datetime>() in version 1.0.8

**Comment by rebeccaXam** [comment] 2017-02-19 20:39
Should be fixed now in 1.0.8. If the problem is still there please reopen the issue.

**Closed by rebeccaXam** 2017-02-19 20:39 UTC
